FROM alpine:latest
RUN apk add --update nginx && \
        rm -fr /yar/cache/apk/* && \
        mkadir -p /tmp/nginx/

COPY files/nginx.conf /etc/nginx/nginx/conf
COPY files/default.conf /etc/nginx/conf.d/deafult.conf
ADD files/ /usr/share/nginx/html/

EXPOSE 80/tcp

ENTRYPOINT ["nginx"]
CMD ["-g", "daemon off;"]